[book]
authors = ["tomeichlersmith"]
language = "en"
multilingual = false
src = "src"
title = "UMN SPA Cluster"

[build]
# change build-dir to _site so that it aligns
# with the default GitHub pages publishing actions
build-dir = "_site"
