[book]
authors = ["tomeichlersmith", "UMN-CMS"]
language = "en"
multilingual = false
src = "src"
title = "UMN SPA Cluster"

[output.html]
mathjax-support = true
site-url = "/cluster/"
git-repository-url = "https://github.com/UMN-CMS/cluster/tree/main/"
edit-url-template = "https://github.com/UMN-CMS/cluster/edit/main/{path}"
