[book]
authors = ["tomeichlersmith"]
language = "en"
multilingual = false
src = "src"
title = "UMN SPA Cluster"

[output.html]
mathjax-support = true
site-url = "/umn-cluster/"
git-repository-url = "https://github.com/tomeichlersmith/umn-cluster/tree/main/"
edit-url-template = "https://github.com/tomeichlersmith/umn-cluster/edit/main/{path}"
