executable				= /local/cms/user/eichl008/umn-cluster/proto-cluster/wadud/run_script.sh
transfer_executable = no

should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT

next_job_start_delay	= 3

transfer_input_files = $(input_file)
initial_dir = /local/cms/user/eichl008/umn-cluster/proto-cluster/wadud/output/

arguments = "$BASENAME(input_file) $(output_file) $(xsec) $(pileup_file)"
queue input_file, output_file, xsec, pileup_file from ./list-queue.sh |
